import type { DayType } from "./rules";

export const BREATH_MAP: Record<DayType, { practice: string; title: string; min: number; time: string; posture: string; technique: string; tongue: string; contra: string }> = {
  stable_day: { practice: "lengthened_exhale", title: "Удлинённый выдох 1:2", min: 8, time: "Утро после горячей воды или за 20 мин до обеда.", posture: "Сидя с прямой спиной, ноги на полу.", technique: "Вдох через нос на 4 счёта. Выдох через нос на 8 счётов — плавно.", tongue: "Кончик языка к верхнему нёбу.", contra: "Не на полный желудок." },
  drainage_day: { practice: "nadi_shodhana_gentle", title: "Нади-шодхана мягкая", min: 7, time: "До обеда, 10:00–12:00.", posture: "Сидя с прямой спиной, правая рука в вишну-мудре.", technique: "Закрыть правую ноздрю, вдох через левую 4 счёта, переключить, выдох через правую 4 счёта.", tongue: "Язык к верхнему нёбу.", contra: "Короткие циклы, при головокружении остановиться." },
  caution_day: { practice: "diaphragmatic", title: "Диафрагмальное дыхание", min: 8, time: "Утро после горячей воды или вечер до 17:30.", posture: "Сидя с ровной спиной, руки на нижних рёбрах.", technique: "Вдох через нос 4 счёта — живот расширяется. Выдох 5–6 счётов — живот возвращается.", tongue: "Язык свободно.", contra: "Не увеличивать глубину после 18:00." },
  high_sensitivity_day: { practice: "bhramari", title: "Бхрамари (жужжание пчелы)", min: 4, time: "Вечер 16:00–17:30 или при перегрузе головы.", posture: "Сидя, пальцы мягко закрывают уши.", technique: "Вдох через нос 4 счёта. На выдохе — мягкое гудение «мммм» 6–8 счётов.", tongue: "Язык свободно, губы мягко сомкнуты.", contra: "Не повышать громкость. Прекратить при дискомфорте." },
  ekadashi_day: { practice: "sama_vritti", title: "Самавритти (равные фазы)", min: 6, time: "Середина дня или за 15 мин до обеда.", posture: "Сидя с ровной спиной, руки на коленях.", technique: "Вдох 4 — задержка 4 — выдох 4 — задержка 4. Все фазы равные.", tongue: "Язык к верхнему нёбу.", contra: "Прекратить при спазме. Убрать задержки при тревоге." },
  pradosh_day: { practice: "lengthened_exhale", title: "Удлинённый выдох 1:2", min: 8, time: "Утро или за 20 мин до обеда.", posture: "Сидя с прямой спиной.", technique: "Вдох 4, выдох 8 через нос.", tongue: "Кончик языка к верхнему нёбу.", contra: "Не на полный желудок." },
  recovery_day_after_reduction: { practice: "diaphragmatic", title: "Диафрагмальное дыхание", min: 8, time: "Утро после горячей воды.", posture: "Сидя или полулёжа.", technique: "Вдох 4 — живот расширяется. Выдох 5–6 — живот возвращается.", tongue: "Язык свободно.", contra: "Не увеличивать глубину после 18:00." },
  pre_full_moon_retention_day: { practice: "bhramari", title: "Бхрамари (жужжание пчелы)", min: 4, time: "Вечер 16:00–17:30.", posture: "Сидя, пальцы закрывают уши.", technique: "Вдох 4, выдох с гудением 6–8 счётов.", tongue: "Язык свободно.", contra: "Не при давлении в голове." },
  pre_new_moon_precision_day: { practice: "diaphragmatic", title: "Диафрагмальное дыхание", min: 8, time: "Утро.", posture: "Сидя с ровной спиной.", technique: "Вдох 4, выдох 5–6.", tongue: "Язык свободно.", contra: "Не увеличивать интенсивность." },
};
