import type { SignalRule } from "../protocol-rules";

/**
 * Порядок оценки задаётся `priority` (asc). Подставьте свои правила; шаблоны — только id из реестров.
 */
export const PROTOCOL_RULES: SignalRule[] = [
  {
    id: "ekadashi_day",
    priority: 10,
    signal: "Экадаши",
    condition: { field: "ekadashiFlag", op: "true" },
    lunchTemplateIds: ["ekadashi_veg"],
    breathingTemplateIds: ["full_soft_6", "sama_vritti_6"],
    loadTemplateId: "very_light",
    warning: "Экадаши: без мяса и рыбы по вашему списку; нагрузка минимальная.",
  },
  {
    id: "pradosh_day",
    priority: 15,
    signal: "Прадош",
    condition: { field: "pradoshFlag", op: "true" },
    lunchTemplateIds: ["pradosh_chicken", "pradosh_veal"],
    breathingTemplateIds: ["extended_exhale_6", "diaphragmatic_8"],
    loadTemplateId: "soft_movement",
    warning: "День Прадоша — обед легче, без тяжёлой нагрузки.",
  },
  {
    id: "day_after_ekadashi",
    priority: 20,
    signal: "День после экадаши",
    condition: { field: "dayAfterEkadashiFlag", op: "true" },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["diaphragmatic_8", "sama_vritti_6"],
    loadTemplateId: "reduced_load",
    warning: "После экадаши — мягкий выход: не перегружать пищу и движение.",
  },
  {
    id: "pre_full_moon_retention",
    priority: 25,
    signal: "Перед полнолунием (удержание)",
    condition: { field: "preFullMoonFlag", op: "true" },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["sama_vritti_8", "extended_exhale_6"],
    loadTemplateId: "soft_movement",
    warning: "Фон удержания жидкости — проще обед, мягкая нагрузка.",
  },
  {
    id: "waning_mid_cycle_drainage",
    priority: 30,
    signal: "Середина убывающей (дренаж)",
    condition: {
      and: [
        { field: "waningPhase", op: "true" },
        { field: "lunarDay", op: "gte", value: 8 },
        { field: "lunarDay", op: "lte", value: 18 },
      ],
    },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["extended_exhale_8", "sama_vritti_8"],
    loadTemplateId: "normal_walk",
    warning: "Убывающая фаза — можно поддерживать умеренное движение при хороших сигналах.",
  },
  {
    id: "pre_new_moon_tail",
    priority: 35,
    signal: "Перед новолунием",
    condition: { field: "preNewMoonFlag", op: "true" },
    lunchTemplateIds: ["pre_new_moon_light"],
    breathingTemplateIds: ["full_soft_6", "extended_exhale_6"],
    loadTemplateId: "very_light",
    warning: "Перед новолунием — максимально лёгкий обед и движение.",
  },
  {
    id: "ankle_swelling",
    priority: 40,
    signal: "Отёк лодыжек вечером",
    condition: { field: "ankleSwellingEvening", op: "gte", value: 3 },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["diaphragmatic_8", "sama_vritti_6"],
    loadTemplateId: "soft_movement",
    warning: "Отёк лодыжек — без гарнира, нагрузка только мягкая.",
  },
  {
    id: "eye_swelling",
    priority: 45,
    signal: "Отёк под глазами утром",
    condition: { field: "eyeSwellingMorning", op: "gte", value: 3 },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["diaphragmatic_8"],
    loadTemplateId: "soft_movement",
    warning: "Отёк зоны глаз — упростить обед и соль.",
  },
  {
    id: "tissue_heaviness",
    priority: 48,
    signal: "Тяжесть тканей",
    condition: { field: "tissueHeaviness", op: "gte", value: 4 },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["extended_exhale_8", "diaphragmatic_8"],
    loadTemplateId: "reduced_load",
    warning: "Тяжесть тканей — снизить нагрузку и упростить тарелку.",
  },
  {
    id: "mental_overheat",
    priority: 50,
    signal: "Перегруз головы",
    condition: { field: "mentalOverload", op: "gte", value: 4 },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["bhramari_5", "extended_exhale_8", "diaphragmatic_8"],
    loadTemplateId: "reduced_load",
    warning: "Перегруз головы — успокаивающее дыхание, сниженная нагрузка.",
  },
  {
    id: "poor_sleep",
    priority: 55,
    signal: "Плохой сон",
    condition: { field: "sleepQuality", op: "lte", value: 2 },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["full_soft_6", "extended_exhale_6"],
    loadTemplateId: "very_light",
    warning: "Плохой сон — не наращивать нагрузку до восстановления сна.",
  },
  {
    id: "sweet_craving_on_fatigue",
    priority: 58,
    signal: "Тяга к сладкому на фоне усталости",
    condition: {
      and: [
        { field: "sweetCraving", op: "gte", value: 4 },
        { field: "energy", op: "lte", value: 2 },
      ],
    },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["sama_vritti_6", "diaphragmatic_8"],
    loadTemplateId: "reduced_load",
    warning: "Сладкое на фоне упадка сил — не компенсировать сахаром, держать обед стабильным.",
  },
  {
    id: "salt_craving",
    priority: 60,
    signal: "Тяга к солёному",
    condition: { field: "saltCraving", op: "gte", value: 4 },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["extended_exhale_6", "sama_vritti_6"],
    loadTemplateId: "soft_movement",
    warning: "Сильная тяга к соли — контроль соли и удержание жидкости.",
  },
  {
    id: "low_energy_with_swelling",
    priority: 65,
    signal: "Низкая энергия с отёками",
    condition: {
      and: [
        { field: "energy", op: "lte", value: 2 },
        {
          or: [
            { field: "ankleSwellingEvening", op: "gte", value: 3 },
            { field: "eyeSwellingMorning", op: "gte", value: 3 },
          ],
        },
      ],
    },
    lunchTemplateIds: ["retention_chicken", "retention_veal"],
    breathingTemplateIds: ["diaphragmatic_8", "full_soft_6"],
    loadTemplateId: "very_light",
    warning: "Мало сил и отёки — без риса, минимум нагрузки.",
  },
  {
    id: "low_energy_no_swelling",
    priority: 70,
    signal: "Низкая энергия без отёков",
    condition: {
      and: [
        { field: "energy", op: "lte", value: 2 },
        { field: "ankleSwellingEvening", op: "lte", value: 2 },
        { field: "eyeSwellingMorning", op: "lte", value: 2 },
      ],
    },
    lunchTemplateIds: ["low_energy_rice_chicken", "low_energy_rice_veal"],
    breathingTemplateIds: ["sama_vritti_8", "diaphragmatic_8"],
    loadTemplateId: "reduced_load",
    warning: "Низкая энергия без отёков — небольшая порция риса допустима по согласованной схеме.",
  },
  {
    id: "stable_state",
    priority: 1000,
    signal: "Стабильное состояние",
    condition: { and: [] },
    lunchTemplateIds: ["stable_chicken", "stable_veal"],
    breathingTemplateIds: ["sama_vritti_8", "diaphragmatic_8"],
    loadTemplateId: "normal_walk",
    warning: "",
  },
];
